version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hUUqDyhEKXSmwTU7i2xk
      - POSTGRES_HOST_AUTH_METHOD=trust
  restapi:
    build: ./Backend
    volumes:
      - ./Backend:/usr/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hUUqDyhEKXSmwTU7i2xk
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  web:
    build: ./Frontend
    volumes:
      - ./Frontend:/usr/app
    ports:
      - "8080:8080"
    command: node_modules/http-server/bin/http-server
    depends_on:
      - restapi
