version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hUUqDyhEKXSmwTU7i2xk
  restapi:
    build: ./Backend
    container_name: restapi
    volumes:
      - ./Backend:/usr/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hUUqDyhEKXSmwTU7i2xk
    depends_on:
      - db
  web:
    build: ./Frontend
    container_name: frontend
    volumes:
      - ./Frontend:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - restapi
