# Generated by Django 4.0.4 on 2022-05-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='number',
            new_name='code',
        ),
    ]
