# Generated by Django 4.0.4 on 2022-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0002_rename_number_airport_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='timezone_offset',
            new_name='timezone_hours',
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
