# Generated by Django 4.0.4 on 2022-05-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0006_remove_booking_rentalcar_booking_rentalcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroplane',
            name='tail_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='travelinsurance',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
