# Generated by Django 4.0.4 on 2022-05-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0007_alter_aeroplane_tail_number_alter_airport_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flightLegs',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='BookingAPI.passenger'),
        ),
    ]
