# Generated by Django 4.0.4 on 2022-05-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0011_alter_passenger_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrabag',
            name='flightLegs',
        ),
        migrations.AddField(
            model_name='extrabag',
            name='flightLeg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.flightleg'),
        ),
        migrations.AddField(
            model_name='extrabag',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.passenger'),
        ),
    ]
