# Generated by Django 4.0.4 on 2022-05-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0013_alter_extrabag_flightleg_alter_extrabag_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='passengers',
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightLeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.flightleg')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.seat')),
            ],
        ),
    ]
