# Generated by Django 4.0.4 on 2022-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0014_remove_seat_passengers_bookedseat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookedseat',
            constraint=models.UniqueConstraint(fields=('seat', 'passenger', 'flightLeg'), name='unique_booking'),
        ),
    ]
