# Generated by Django 4.0.4 on 2022-05-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0016_alter_flightleg_aeroplane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightleg',
            name='aeroplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightLegs', to='BookingAPI.aeroplane'),
        ),
    ]
