# Generated by Django 4.0.4 on 2022-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0019_flightleg_flight_time_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightleg',
            name='arrival_date_time_utc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='departure_date_time_utc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
