# Generated by Django 4.0.4 on 2022-05-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0021_alter_flightleg_arrival_date_time_utc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightleg',
            name='number',
            field=models.CharField(max_length=8),
        ),
    ]
