# Generated by Django 4.0.4 on 2022-06-18 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0024_alter_airport_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=12345, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
    ]
