# Generated by Django 4.0.4 on 2022-06-23 06:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=8, unique=True)),
                ('make_model', models.CharField(max_length=64)),
                ('num_seats', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('image_link', models.CharField(max_length=512, null=True)),
                ('floor_plan_link', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('timezone', models.CharField(default='Pacific/Auckland', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BookingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=12345, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('image_link', models.CharField(max_length=512, null=True)),
                ('web_link', models.CharField(max_length=512, null=True)),
                ('cost_per_day', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='TravelInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('image_link', models.CharField(max_length=512, null=True)),
                ('web_link', models.CharField(max_length=512, null=True)),
                ('cost_per_person', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('emergency_exit', models.BooleanField(default=False)),
                ('aeroplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.aeroplane')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('special_assistance', models.CharField(max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('cost_dollars', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('departure_date_time_utc', models.DateTimeField(auto_now_add=True)),
                ('arrival_date_time_utc', models.DateTimeField(auto_now_add=True)),
                ('flight_time_mins', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('aeroplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightLegs', to='BookingAPI.aeroplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='BookingAPI.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='BookingAPI.airport')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('flightLeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.flightleg')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flightLegs', models.ManyToManyField(to='BookingAPI.flightleg')),
                ('passengers', models.ManyToManyField(to='BookingAPI.passenger')),
                ('rentalCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.rentalcar')),
                ('travelInsurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.travelinsurance')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.booking')),
                ('flightLeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.flightleg')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookedseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat', 'passenger', 'flightLeg'), name='unique_booking'),
        ),
    ]
