# Generated by Django 4.0.4 on 2022-05-02 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=8)),
                ('make_model', models.CharField(max_length=64)),
                ('num_seats', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('timezone_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('cost_dollars', models.IntegerField(default=100)),
                ('departure_time_of_day', models.TimeField()),
                ('flight_time_minutes', models.BigIntegerField(default=60)),
                ('departs_sun', models.BooleanField(default=False)),
                ('departs_mon', models.BooleanField(default=False)),
                ('departs_tue', models.BooleanField(default=False)),
                ('departs_wed', models.BooleanField(default=False)),
                ('departs_thu', models.BooleanField(default=False)),
                ('departs_fri', models.BooleanField(default=False)),
                ('departs_sat', models.BooleanField(default=False)),
                ('aeroplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.aeroplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='BookingAPI.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='BookingAPI.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('special_assistance', models.CharField(max_length=128)),
                ('flightLegs', models.ManyToManyField(to='BookingAPI.flightleg')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('image_link', models.CharField(max_length=512)),
                ('web_link', models.CharField(max_length=512)),
                ('cost_per_day', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('image_link', models.CharField(max_length=512)),
                ('web_link', models.CharField(max_length=512)),
                ('cost_per_person', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('emergency_exit', models.BooleanField(default=False)),
                ('aeroplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.aeroplane')),
                ('passengers', models.ManyToManyField(to='BookingAPI.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=10)),
                ('flightLegs', models.ManyToManyField(to='BookingAPI.flightleg')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('flightLegs', models.ManyToManyField(to='BookingAPI.flightleg')),
                ('rentalCar', models.ManyToManyField(to='BookingAPI.rentalcar')),
                ('travelInsurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.travelinsurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
