# Generated by Django 4.0.4 on 2022-06-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='BookingAPI.booking'),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='flightLeg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightLeg', to='BookingAPI.flightleg'),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='BookingAPI.passenger'),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='BookingAPI.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rentalCar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentalCar', to='BookingAPI.rentalcar'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travelInsurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travelInsurance', to='BookingAPI.travelinsurance'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='aeroplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeroplaneFlight', to='BookingAPI.aeroplane'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='aeroplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeroplaneSeat', to='BookingAPI.aeroplane'),
        ),
    ]
