# Generated by Django 4.0.4 on 2022-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0002_alter_bookedseat_booking_alter_bookedseat_flightleg_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookedseat',
            name='unique_booking',
        ),
        migrations.RemoveField(
            model_name='bookedseat',
            name='booking',
        ),
        migrations.AddConstraint(
            model_name='bookedseat',
            constraint=models.UniqueConstraint(fields=('seat', 'passenger', 'flightLeg'), name='unique_booking'),
        ),
    ]
