# Generated by Django 4.0.4 on 2022-05-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0004_remove_extrabag_weight_extrabag_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flightLegs',
            field=models.ManyToManyField(to='BookingAPI.flightleg'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rentalCar',
            field=models.ManyToManyField(to='BookingAPI.rentalcar'),
        ),
        migrations.AlterField(
            model_name='extrabag',
            name='flightLegs',
            field=models.ManyToManyField(to='BookingAPI.flightleg'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flightLegs',
            field=models.ManyToManyField(to='BookingAPI.flightleg'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='passengers',
            field=models.ManyToManyField(to='BookingAPI.passenger'),
        ),
    ]
