# Generated by Django 4.0.4 on 2022-06-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0004_alter_booking_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLegStopover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightLegA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightLegA', to='BookingAPI.flightleg')),
                ('flightLegB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightLegB', to='BookingAPI.flightleg')),
                ('stopoverAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover', to='BookingAPI.airport')),
            ],
        ),
    ]
