# Generated by Django 4.0.4 on 2022-05-03 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookingAPI', '0008_remove_passenger_flightlegs_booking_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
