# Generated by Django 4.0.4 on 2022-05-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0009_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='user',
            new_name='created_by',
        ),
    ]
