# Generated by Django 4.0.4 on 2022-05-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0012_remove_extrabag_flightlegs_extrabag_flightleg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrabag',
            name='flightLeg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.flightleg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrabag',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookingAPI.passenger'),
            preserve_default=False,
        ),
    ]
