# Generated by Django 4.0.4 on 2022-05-29 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0018_remove_flightleg_departs_fri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='flight_time_mins',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
