# Generated by Django 4.0.4 on 2022-05-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0022_alter_flightleg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='timezone_hours',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='timezone_minutes',
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='Pacific/Auckland', max_length=256),
        ),
    ]
