# Generated by Django 4.0.4 on 2022-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0023_remove_airport_timezone_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='Pacific/Auckland', max_length=128),
        ),
    ]
