# Generated by Django 4.0.4 on 2022-06-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0025_bookingnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroplane',
            name='image_link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
